version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.1

  bash <(curl -s https://codecov.io/bash)

  - codecov/upload:
    file: "./coverage/clover.xml"

workflows:
  node-tests:
    jobs:
      - node/test
