version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.1
  cypress: cypress-io/cypress@1.26.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: run tests and generate coverage
          command: npm run cov
      - codecov/upload:
          file: ./coverage/clover.xml
      - run:
          name: build
          command: CI=false npm run build
  cypress:
    steps:
      - run:
          name: Cypress Install
          command: npm i cypress
      - run:
          name: Cypress Run
          command: npm run ci

workflows:
  node-tests:
    jobs:
      - node/test
      - 'build'
      - 'cypress'
