version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - codecov/upload:
          file: ../coverage/clover.xml

workflows:
  node-tests:
    jobs:
      - node/test
      - build
